from .rt_users import UsersRoutes
from .rt_commodities import CommoditiesRoutes
from .rt_auth import AuthRoutes
from .rt_transactions import TransactionsRoutes
from .rt_accounts import AccountsRoutes
from .rt_budgets import BudgetsRoutes
from .rt_categories import CategoriesRoutes
from .rt_institutions import InstitutionsRoutes
from .rt_tags import TagsRoutes
from .rt_subscriptions import SubscriptionsRoutes
from .rt_dashboard import DashboardRoutes
from .rt_assets import AssetsRoutes
from .rt_dca import DcaRoutes
from .rt_reports import ReportsRoutes
from .rt_roles import RolesRoutes
from .rt_import import ImportRoutes
from .rt_documents import DocumentsRoutes
from .rt_reconcile import ReconcileRoutes
from .rt_test import TestRoutes
from .rt_markets import MarketsRoutes
from .rt_wealth import WealthRoutes
from .rt_settings import SettingsRoutes
from .rt_backup import BackupRoutes
from .rt_custom_reports import CustomReportsRoutes
from .rt_loans import LoansRoutes
from .rt_onboarding import OnboardingRoutes
from .rt_tax import TaxRoutes
from .rt_forecast import ForecastRoutes
from .rt_goals import GoalsRoutes
