"""initial schema

Revision ID: 0bee1c5b7470
Revises: 
Create Date: 2026-07-13 01:02:00.540824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bee1c5b7470'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_code', sa.String(length=10), nullable=False),
    sa.Column('to_code', sa.String(length=10), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_code', 'to_code', 'rate_date')
    )
    op.create_table('market_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index_name', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name', 'ticker')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=256), nullable=False),
    sa.Column('salt', sa.LargeBinary(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('budgets',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(), nullable=False),
    sa.Column('amount_spent', sa.Numeric(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_table('commodities',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=6), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('fraction', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('track_live_rate', sa.Boolean(), nullable=False),
    sa.Column('last_rate_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("type in ('Currency', 'Crypto')"),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'short_name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("color in ('green', 'red', 'blue', 'white', 'black', 'yellow', 'purple')"),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=6), nullable=False),
    sa.Column('date_format', sa.String(length=16), nullable=False),
    sa.Column('market_score_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_score_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker')
    )
    op.create_table('wealth_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('bank_net_worth', sa.Numeric(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date')
    )
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('account_subtype', sa.String(length=64), nullable=True),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('total_spent', sa.Numeric(), nullable=False),
    sa.Column('total_earned', sa.Numeric(), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(account_type = 'Equity' AND account_subtype IN ('fr_PEA', 'Other')) OR account_subtype is NULL"),
    sa.CheckConstraint("account_type IN ('Income', 'Expense', 'Equity', 'Assets', 'Current')"),
    sa.ForeignKeyConstraint(['currency_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_table('assets',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('commodity_id', sa.UUID(), nullable=True),
    sa.Column('value_per_unit', sa.Numeric(), nullable=False),
    sa.Column('track_live_price', sa.Boolean(), nullable=False),
    sa.Column('last_price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("asset_type IN ('Stock', 'ETF') OR sector IS NULL"),
    sa.CheckConstraint("asset_type IN ('Stock', 'ETF', 'RealEstate', 'Vehicle', 'Other')"),
    sa.CheckConstraint("track_live_price = false OR asset_type IN ('Stock', 'ETF')"),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'asset_type', 'commodity_id')
    )
    op.create_table('budget_categories',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budget_id', 'category_id')
    )
    op.create_table('budget_tags',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budget_id', 'tag_id')
    )
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_cleared', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_id'], ['commodities.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('budget_accounts',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budget_id', 'account_id')
    )
    op.create_table('splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('fx_rate', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('schedule_type', sa.String(length=10), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=True),
    sa.Column('month_of_year', sa.SmallInteger(), nullable=True),
    sa.Column('weekdays', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('from_account_id', sa.UUID(), nullable=True),
    sa.Column('to_account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("schedule_type IN ('monthly', 'yearly', 'weekly')"),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_table('transaction_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed')"),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_possession',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('source_account_id', sa.UUID(), nullable=True),
    sa.Column('tx_id', sa.UUID(), nullable=True),
    sa.Column('source_split_id', sa.UUID(), nullable=True),
    sa.Column('dest_split_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(), nullable=True),
    sa.Column('purchase_price_native', sa.Numeric(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity <= 1000000000 AND quantity >= 0'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dest_split_id'], ['splits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_split_id'], ['splits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_on_split',
    sa.Column('split_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['split_id'], ['splits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('split_id', 'tag_id')
    )
    # ### end Alembic commands ###

    # ── Fonctions et triggers Postgres (non détectés par autogenerate) ──────────
    # Repris tel quel de backend/database/functions/*.py et backend/database/triggers/*.py,
    # jusqu'ici installés via des événements SQLAlchemy DDL 'after_create' dans app.py.
    op.execute("""
    CREATE OR REPLACE FUNCTION check_category_id()
    RETURNS TRIGGER AS $$
    BEGIN
        IF NEW.category_id IS NULL THEN
            RETURN NEW;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM categories WHERE id = NEW.category_id AND user_id = NEW.user_id) THEN
            RAISE EXCEPTION 'Invalid category_id % for user_id %', NEW.category_id, NEW.user_id;
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE OR REPLACE FUNCTION update_account_totals()
    RETURNS TRIGGER AS $$
    DECLARE
        affected_account_id UUID;
    BEGIN
        IF TG_OP = 'UPDATE' AND OLD.account_id IS DISTINCT FROM NEW.account_id THEN
            UPDATE accounts SET
                total_earned = COALESCE((
                    SELECT SUM(quantity) FROM splits
                    WHERE account_id = OLD.account_id AND quantity > 0
                ), 0),
                total_spent = COALESCE((
                    SELECT SUM(-quantity) FROM splits
                    WHERE account_id = OLD.account_id AND quantity < 0
                ), 0)
            WHERE id = OLD.account_id;
        END IF;

        IF TG_OP = 'DELETE' THEN
            affected_account_id := OLD.account_id;
        ELSE
            affected_account_id := NEW.account_id;
        END IF;

        UPDATE accounts SET
            total_earned = COALESCE((
                SELECT SUM(quantity) FROM splits
                WHERE account_id = affected_account_id AND quantity > 0
            ), 0),
            total_spent = COALESCE((
                SELECT SUM(-quantity) FROM splits
                WHERE account_id = affected_account_id AND quantity < 0
            ), 0)
        WHERE id = affected_account_id;

        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        ELSE
            RETURN NEW;
        END IF;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE OR REPLACE FUNCTION update_budget_spent()
    RETURNS TRIGGER AS $$
    DECLARE
        affected_budget RECORD;
        new_amount_spent NUMERIC;
        split_ref RECORD;
    BEGIN
        IF TG_OP = 'DELETE' THEN
            split_ref := OLD;
        ELSE
            split_ref := NEW;
        END IF;

        FOR affected_budget IN
            SELECT DISTINCT b.id, b.start_date, b.end_date
            FROM budgets b
            WHERE
                EXISTS (
                    SELECT 1 FROM budget_accounts ba
                    WHERE ba.budget_id = b.id AND ba.account_id = split_ref.account_id
                )
                OR EXISTS (
                    SELECT 1 FROM budget_categories bc
                    JOIN transactions t ON t.id = split_ref.tx_id
                    WHERE bc.budget_id = b.id
                      AND bc.category_id = t.category_id
                      AND t.category_id IS NOT NULL
                )
                OR EXISTS (
                    SELECT 1 FROM budget_tags bt
                    JOIN tags_on_split tos ON tos.tag_id = bt.tag_id
                    WHERE bt.budget_id = b.id AND tos.split_id = split_ref.id
                )
        LOOP
            SELECT COALESCE(SUM(s.quantity), 0) INTO new_amount_spent
            FROM splits s
            JOIN transactions t ON t.id = s.tx_id
            JOIN accounts a ON a.id = s.account_id
            WHERE
                t.post_date BETWEEN affected_budget.start_date AND affected_budget.end_date
                AND (
                    EXISTS (
                        SELECT 1 FROM budget_accounts ba
                        WHERE ba.budget_id = affected_budget.id AND ba.account_id = s.account_id
                    )
                    OR (
                        a.account_type NOT IN ('Expense', 'Income')
                        AND t.category_id IS NOT NULL
                        AND EXISTS (
                            SELECT 1 FROM budget_categories bc
                            WHERE bc.budget_id = affected_budget.id AND bc.category_id = t.category_id
                        )
                    )
                    OR (
                        a.account_type NOT IN ('Expense', 'Income')
                        AND EXISTS (
                            SELECT 1 FROM tags_on_split tos
                            JOIN budget_tags bt ON bt.tag_id = tos.tag_id
                            WHERE tos.split_id = s.id AND bt.budget_id = affected_budget.id
                        )
                    )
                );

            UPDATE budgets SET amount_spent = new_amount_spent WHERE id = affected_budget.id;
        END LOOP;

        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        ELSE
            RETURN NEW;
        END IF;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE OR REPLACE FUNCTION update_timestamp()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = CURRENT_TIMESTAMP;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trg_check_category_id
        BEFORE INSERT OR UPDATE ON transactions
        FOR EACH ROW
        EXECUTE FUNCTION check_category_id();
    """)
    op.execute("""
        CREATE TRIGGER trg_update_account_totals
        AFTER INSERT OR UPDATE OR DELETE ON splits
        FOR EACH ROW
        EXECUTE FUNCTION update_account_totals();
    """)
    op.execute("""
        CREATE TRIGGER trg_update_budget_spent
        AFTER INSERT OR UPDATE OR DELETE ON splits
        FOR EACH ROW
        EXECUTE FUNCTION update_budget_spent();
    """)
    op.execute("""
        CREATE TRIGGER trg_update_timestamp_accounts
        BEFORE UPDATE ON accounts
        FOR EACH ROW
        EXECUTE FUNCTION update_timestamp();
    """)
    op.execute("""
        CREATE TRIGGER trg_update_timestamp_budgets
        BEFORE UPDATE ON budgets
        FOR EACH ROW
        EXECUTE FUNCTION update_timestamp();
    """)
    op.execute("""
        CREATE TRIGGER trg_update_timestamp_users
        BEFORE UPDATE ON users
        FOR EACH ROW
        EXECUTE FUNCTION update_timestamp();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_update_timestamp_users ON users")
    op.execute("DROP TRIGGER IF EXISTS trg_update_timestamp_budgets ON budgets")
    op.execute("DROP TRIGGER IF EXISTS trg_update_timestamp_accounts ON accounts")
    op.execute("DROP TRIGGER IF EXISTS trg_update_budget_spent ON splits")
    op.execute("DROP TRIGGER IF EXISTS trg_update_account_totals ON splits")
    op.execute("DROP TRIGGER IF EXISTS trg_check_category_id ON transactions")
    op.execute("DROP FUNCTION IF EXISTS update_timestamp()")
    op.execute("DROP FUNCTION IF EXISTS update_budget_spent()")
    op.execute("DROP FUNCTION IF EXISTS update_account_totals()")
    op.execute("DROP FUNCTION IF EXISTS check_category_id()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_on_split')
    op.drop_table('asset_possession')
    op.drop_table('transaction_documents')
    op.drop_table('subscriptions')
    op.drop_table('splits')
    op.drop_table('budget_accounts')
    op.drop_table('transactions')
    op.drop_table('budget_tags')
    op.drop_table('budget_categories')
    op.drop_table('assets')
    op.drop_table('accounts')
    op.drop_table('wealth_snapshot')
    op.drop_table('watchlist')
    op.drop_table('user_settings')
    op.drop_table('user_roles')
    op.drop_table('tags')
    op.drop_table('role_permissions')
    op.drop_table('commodities')
    op.drop_table('categories')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('market_index')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
